In [1]:
import requests
from textblob import TextBlob
import json
import pandas as pd
import numpy as np #Library for advance Numpy functionality
import pandas as pd #Library to make use of Pandas Dataframes
import requests #Library to handle URL requests to get data from Web services.
import urllib.request #Libary to handle request status and data
import time #Libary to manipulate script execution time or to keep track of ellapsed time.
import json #Libary to work smartly with JSON data retrieved from API calls.
from bs4 import BeautifulSoup #Web library to make returned text legible.
import pandas_profiling
import seaborn  as sns
import missingno as msno
from time import sleep

/home/explore/anaconda3/lib/python3.6/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.6) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)

__First Scrape__

In [2]:
test_dictionary = []# create empty dictionary
list1 = []  #empty list
my_list =[] #empty list
for page_number in range(1, 20):# number of pages to be scrapped
    url = f'https://api.hellopeter.com/consumer/business/telkom/reviews?page={page_number}'
    response = requests.get(url).json()
    test_dictionary.append(response) #add json file to dictionary
    for item in response['data']: # items in data inside json file
        #extend empty list with columns you need
        list1.extend((item['id'],item['created_at'],item['email'],item['author_id'],item['author_ip_address'],item['review_title'],item['review_rating'],item['review_content'],item['business_name'],item['permalink'],item['business_logo'],item['industry_logo'],item['industry_name'],item['status_id'],item['nps_rating'],item['is_reported']))

In [3]:
saved_ids = [] # empty list

for i in range(test_dictionary.__len__()):
    for p in test_dictionary[i]['data']:
        saved_ids.append(p['id'])# save ids to 'saved_ids' from data of first scrape

In [4]:
dat1 = [] # empty list
new_ids = [] # empty list
for page_number in range(15, 25): #number of pages to scrape
    url = f'https://api.hellopeter.com/consumer/business/telkom/reviews?page={page_number}'
    response = requests.get(url).json()
  
    for item in response['data']:
        if item['id'] not in saved_ids: # check if id is not in the list of above ids
            new_ids.append(item['id']), # if not add to this list
            #extend empty list with columns you need
            dat1.extend((item['id'],item['created_at'],item['email'],item['author_id'],item['author_ip_address'],item['review_title'],item['review_rating'],item['review_content'],item['business_name'],item['permalink'],item['business_logo'],item['industry_logo'],item['industry_name'],item['status_id'],item['nps_rating'],item['is_reported']))
        else:
                                                                                                                                                      
            continue

In [5]:
The_ids = [] # empty list
new_list =[] # empty list
The_list = dat1 + list1 # Combine two lists with the columns we need
for i in range(16,len(dat1)+16,16):
    if i ==16:
        new_list.append(dat1[:i])
        
    else:
        new_list.append(dat1[i-16:i])

In [6]:
from pandas import DataFrame

__Creating data frame__

In [7]:
df = DataFrame(new_list,columns=['id','created_at','email','author_id','author_ip_address','review_title','review_rating','review_content','business_name','permalink','business_logo','industry_logo','industry_name','status_id','nps_rating','is_reported'])

In [27]:
df.head()

,id,created_at,email,author_id,author_ip_address,review_title,review_rating,review_content,business_name,permalink,business_logo,industry_logo,industry_name,status_id,nps_rating,is_reported
0,2889983,2019-10-21 13:13:14,justin.stent@gmail.com,62919c20-f3f1-11e9-9db5-53676c5d3bbf,197.245.61.169,Telkom fibre upgrade nightmare,1,I applied for an upgrade from 10 Mbps on fibre...,Telkom,telkom-fibre-upgrade-nightmare-a8e7ea718c8706f...,https://s3-us-west-2.amazonaws.com/hp-cdn-01/u...,/static/img/industries/icons/telecommunication...,Telecommunications,1,2.0,False
1,2889974,2019-10-21 13:07:34,bianca@cibecs.com,323d8795-31fa-11e8-83f4-f23c91bb6188,105.27.176.74,May I add a contract please?!?!?!,1,"Telkom, oh Telkom, please just take my money a...",Telkom,may-i-add-a-contract-please-2889974,https://s3-us-west-2.amazonaws.com/hp-cdn-01/u...,/static/img/industries/icons/telecommunication...,Telecommunications,1,NaN,False
2,2889959,2019-10-21 12:50:47,ALPHASTUDIO@TELKOMSA.NET,3f0133b0-f3e7-11e9-b317-5fa025377d54,105.226.8.107,WITHOUT PHONE LINES AND ADSL NETWORK THE BUSIN...,1,"On May 2019, we Reported a fault on our landl...",Telkom,without-phone-lines-and-adsl-network-the-busin...,https://s3-us-west-2.amazonaws.com/hp-cdn-01/u...,/static/img/industries/icons/telecommunication...,Telecommunications,1,NaN,False
3,2889957,2019-10-21 12:49:37,gabr435@gmail.com,abe1e320-f3ec-11e9-b5be-3f2e6b75fa77,41.113.160.160,Rep off and dissatisfied,1,Telkom is seriously a joke @telkom Iâ€™m ****ed ...,Telkom,rep-off-and-dissatisfied-2889957,https://s3-us-west-2.amazonaws.com/hp-cdn-01/u...,/static/img/industries/icons/telecommunication...,Telecommunications,1,NaN,False
4,2889952,2019-10-21 12:46:21,pwallace10@gmail.com,fa207fdd-31f9-11e8-83f4-f23c91bb6188,154.72.101.173,Telkom still dont care..,1,My poor mom in law was called by a Telkom pers...,Telkom,telkom-still-dont-care-2889952,https://s3-us-west-2.amazonaws.com/hp-cdn-01/u...,/static/img/industries/icons/telecommunication...,Telecommunications,1,0.0,False

In [25]:
len(df)

55

__Geolite API__

In [9]:
import pandas as pd
from geolite2 import geolite2

In [81]:
#Use IP Address to get location
def get_location(ip):
    try:
        x = geolite2.reader().get(ip)
    except ValueError:
        return {'Continent': 'None','Country': 'None','City': 'None','Latitude': 'None','Longitude': 'None','Postal Code': 'None','Province': 'None'}
    
    try:
        return {'Continent':x['continent']['names']['en'],'Country':x['country']['names']['en'],'City':x['city']['names']['en'],'Latitude':x['location']['latitude'],'Longitude':x['location']['longitude'],'Postal Code':x['postal']['code'],'Province':x['subdivisions'][0]['names']['en']} 
    except KeyError:
        
        return {'Continent': 'None','Country': 'None','City': 'None','Latitude': 'None','Longitude': 'None','Postal Code': 'None','Province': 'None'}

In [82]:
List_df =[]

for i in range(len(df)):
   
    List_df.append(get_location(df.author_ip_address[i]))

In [83]:
Loc =pd.DataFrame(List_df)

In [84]:
new_df = df.join(Loc)
new_df.head()

,id,created_at,email,author_id,author_ip_address,review_title,review_rating,review_content,business_name,permalink,...,status_id,nps_rating,is_reported,City,Continent,Country,Latitude,Longitude,Postal Code,Province
0,2889983,2019-10-21 13:13:14,justin.stent@gmail.com,62919c20-f3f1-11e9-9db5-53676c5d3bbf,197.245.61.169,Telkom fibre upgrade nightmare,1,I applied for an upgrade from 10 Mbps on fibre...,Telkom,telkom-fibre-upgrade-nightmare-a8e7ea718c8706f...,...,1,2.0,False,Alberton,Africa,South Africa,-26.2333,28.1333,1451,Gauteng
1,2889974,2019-10-21 13:07:34,bianca@cibecs.com,323d8795-31fa-11e8-83f4-f23c91bb6188,105.27.176.74,May I add a contract please?!?!?!,1,"Telkom, oh Telkom, please just take my money a...",Telkom,may-i-add-a-contract-please-2889974,...,1,NaN,False,Johannesburg,Africa,South Africa,-26.2309,28.0583,2188,Gauteng
2,2889959,2019-10-21 12:50:47,ALPHASTUDIO@TELKOMSA.NET,3f0133b0-f3e7-11e9-b317-5fa025377d54,105.226.8.107,WITHOUT PHONE LINES AND ADSL NETWORK THE BUSIN...,1,"On May 2019, we Reported a fault on our landl...",Telkom,without-phone-lines-and-adsl-network-the-busin...,...,1,NaN,False,Howick,Africa,South Africa,-29.5167,30.2333,3290,KwaZulu-Natal
3,2889957,2019-10-21 12:49:37,gabr435@gmail.com,abe1e320-f3ec-11e9-b5be-3f2e6b75fa77,41.113.160.160,Rep off and dissatisfied,1,Telkom is seriously a joke @telkom Iâ€™m ****ed ...,Telkom,rep-off-and-dissatisfied-2889957,...,1,NaN,False,Krugersdorp,Africa,South Africa,-26.1,27.7667,1739,Gauteng
4,2889952,2019-10-21 12:46:21,pwallace10@gmail.com,fa207fdd-31f9-11e8-83f4-f23c91bb6188,154.72.101.173,Telkom still dont care..,1,My poor mom in law was called by a Telkom pers...,Telkom,telkom-still-dont-care-2889952,...,1,0.0,False,Cape Town,Africa,South Africa,-33.9167,18.4167,7441,Western Cape